import logo from "../assets/images/logo.svg";
import Spinner from "../assets/images/SpinnerLoader.svg";
import MainSpinner from "../assets/images/mainLoader.svg";
import EyeOpen from "../assets/images/EyeOpen.svg";
import EyeOff from "../assets/images/EyeOff.svg";
import checkCircle from "../assets/images/checkCircle.svg";
import HumbergerIcon from "../assets/images/Humberger.svg";
import ChangePasswordIcon from "../assets/images/ChangePassIcon.svg";
import LogoutIcon from "../assets/images/Logout.svg";
import ExpandMoreIcon from "../assets/images/expandMoreIcon.svg";
import ProfileIcon from "../assets/images/Profile.svg";
import MoreIcon from "../assets/images/More.svg";
import ChevronRightIcon from "../assets/images/chevronRight.svg";
import NoDataImg from "../assets/images/noDataImg.svg";
import DownloadBtnSpinner from "../assets/images/downloadButtonSpinner.svg";
import ChevronLeftIcon from "../assets/images/chevronLeft.svg";
import ChevronRightPaginationIcon from "../assets/images/chevronRightPagination.svg";
import nextArrow from "../assets/images/nextArrow.svg";
import prevArrow from "../assets/images/prevArrow.svg";
import expandMoreOppIcon from "../assets/images/expand_more.png";
import fileDownload from "../assets/images/FileDownload.svg";

export const LOGO = logo;
export const BUTTON_SPINNER = Spinner;
export const MAIN_SPINNER = MainSpinner;
export const EYE_OPEN = EyeOpen;
export const EYE_OFF = EyeOff;
export const CHECK_CIRCLE = checkCircle;
export const HUMBERGER_ICON = HumbergerIcon;
export const CHANGE_PASSWORD_ICON = ChangePasswordIcon;
export const LOGOUT_ICON = LogoutIcon;
export const EXPAND_MORE_ICON = ExpandMoreIcon;
export const PROFILE_ICON = ProfileIcon;
export const MORE_ICON = MoreIcon;
export const CHEVRON_RIGHT_ICON = ChevronRightIcon;
export const NO_DATA_IMG = NoDataImg;
export const BOWNLOAD_BUTTON_SPINNER = DownloadBtnSpinner;
export const CHEVRON_LEFT_ICON = ChevronLeftIcon;
export const CHEVRON_RIGHT_PAGINATION_ICON = ChevronRightPaginationIcon;
export const NEXT_ARROW = nextArrow;
export const PREV_ARROW = prevArrow;
export const EXPAND_MORE_ICON_OPP = expandMoreOppIcon;
export const FILE_DOWNLOAD = fileDownload;
